main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('help/', views.help, name='help'),
	path('subforums/new/', views.subforums_new, name='subforums_new'),
	path('subforums/create/', views.subforums_create, name='subforums_create'),
	path('subforums/<int:subforum_id>/', views.subforums_detail, name='subforums_detail'),
	path('subforums/<int:subforum_id>/like/', views.subforums_like, name='subforums_like'),
	path('subforums/<int:pk>/update/', views.SubforumUpdate.as_view(), name='subforums_update'),
	path('subforums/<int:subforum_id>/add_post/', views.add_post, name='add_post'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/update/', views.update_post, name='update_post'),
	path('subforums/<int:subforum_id>/post/<int:pk>/delete/', views.PostDelete.as_view(), name='delete_post'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/comment/<int:pk>/delete_comment/', views.CommentDelete.as_view(), name='delete_comment'),
	path('company/', views.CompanyList.as_view(), name='company_index'),
	path('company/<int:pk>/', views.CompanyDetail.as_view(), name='company_detail'),
	path('company/create/', views.CompanyCreate.as_view(), name='company_create'),
	path('company/<int:company_id>/subforums/new/', views.company_subforums_new, name='company_subforums_new'),
	path('company/<int:company_id>/subforums/create/', views.company_subforums_create, name='company_subforums_create'),
	path('company/<int:company_id>/subforums/<int:pk>/update/', views.Company_SubforumUpdate.as_view(), name='company_subforums_update'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/', views.company_subforums_detail, name='company_subforums_detail'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/like/', views.company_subforums_like, name='company_subforums_like'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/add_post/', views.add_company_post, name='add_company_post'),
    path('company/<int:company_id>/subforums/<int:company_subforum_id>/post/<int:company_post_id>/add_comment/', views.add_company_comment, name='add_company_comment'),
    path('company/<int:company_id>/subforums/<int:company_subforum_id>/post/<int:company_post_id>/comment/<int:pk>/delete/', views.Company_CommentDelete.as_view(), name='delete_company_comment'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/posts/<int:company_post_id>/update/', views.update_company_post, name='update_company_post'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/posts/<int:pk>/delete/', views.Company_PostDelete.as_view(), name='delete_company_post'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/<int:user_id>/application/new/', views.applications_new, name='applications_new'),
    path('profile/<int:user_id>/application/create/', views.applications_create, name='applications_create'),
    path('profile/<int:user_id>/application/<int:application_id>/', views.applications_detail, name='applications_detail'),
    path('profile/<int:user_id>/application/<int:pk>/delete/', views.Job_ApplicationDelete.as_view(), name='applications_delete'),
    path('profile/<int:user_id>/application/<int:pk>/update/', views.Job_ApplicationUpdate.as_view(), name='applications_update'),
    path('profile/<int:user_id>/application/<int:application_id>/status_update/', views.status_update, name='status_update'),
    path('profile/<int:user_id>/application/<int:application_id>/add_component/', views.add_component, name='add_component'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:pk>/delete/', views.Application_ComponentDelete.as_view(), name='delete_component'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:component_id>/add_note/', views.add_note, name='add_note'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:component_id>/note/<int:pk>/delete/', views.Component_NoteDelete.as_view(), name='delete_note'),
    path('profile/<int:user_id>/liked/', views.liked, name='liked'),
  	path('accounts/signup/', views.signup, name='signup'), 
	path('faq/', views.faq, name='faq')
]

thedraft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date, datetime
from django.contrib.auth.models import User 
# Create your models here.


class Subforum(models.Model): 
    title = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    pinned = models.BooleanField(default=False)
    content = models.TextField(max_length=600)
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'title of this subforum: {self.title}'
    
    def get_absolute_url(self): 
        return reverse('subforums_detail', kwargs={'subforum_id': self.id})  #refactor with the correct views reference and variable names 
    
class Subforum_Likes(models.Model): 
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    subforum = models.ForeignKey(
        Subforum, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'likes model {self.id} '

    
class Post(models.Model): 
    content = models.TextField(max_length=600)
    date = models.DateField(auto_now_add=True)
    subforum = models.ForeignKey(
        Subforum, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
  
    def __str__(self):
        return f'the id of this post is {self.id}'
    
    def get_absolute_url(self): 
        return reverse('subforums_detail', kwargs={'subforum_id': self.subforum.id}) 

    class Meta: 
        ordering = ['-date']

class Photo(models.Model): 
    url = models.CharField(max_length=200)
    subforum = models.ForeignKey(
        Subforum, 
        on_delete=models.CASCADE
        )
    

    def __str__(self):
        return f'photo id: {self.id} @{self.url}'



class Comment(models.Model): 
    content = models.TextField(max_length=250)
    date = models.DateField(auto_now_add=True)
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'comment id: {self.id}'

    class Meta: 
        ordering = ['-date']

class Company(models.Model): 
    name =  models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    url = models.CharField(max_length=150, verbose_name='Company Job Postings URL')
    industry = models.CharField(max_length=100)
    photo_url = models.CharField(max_length=150)

    def __str__(self): 
        return f'{self.name}'
    
    def get_absolute_url(self): 
        return reverse('company_detail', kwargs={'pk': self.id})  #refactor with the correct views reference and variable names 
    

class Company_Subforum(models.Model): 
    title = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    pinned = models.BooleanField(default = False)
    content = models.TextField(max_length=600)
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'title subforum: {self.title}'
    
    def get_absolute_url(self): 
        return reverse('company_subforums_detail', kwargs={
            'company_id': self.company_id,
            'company_subforum_id': self.id
            })  #refactor with the correct views reference and variable names 

class Company_Subforum_Likes(models.Model): 
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    subforum = models.ForeignKey(
        Company_Subforum, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'likes model {self.id} '
    
class Company_Post(models.Model): 
    content = models.TextField(max_length=600)
    date = models.DateField(auto_now_add=True)
    subforum = models.ForeignKey(
        Company_Subforum, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
  
    def __str__(self):
        return f'post id: {self.id}'

    class Meta: 
        ordering = ['-date']

class Company_Comment(models.Model): 
    content = models.TextField(max_length=250)
    date = models.DateField(auto_now_add=True)
    post = models.ForeignKey(
        Company_Post, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    def __str__(self):
        return f'comment id: {self.id}'

    class Meta: 
        ordering = ['-date']

class Company_Photo(models.Model): 
    url = models.CharField(max_length=200)
    subforum = models.ForeignKey(
        Company_Subforum, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'Photo id: {self.id} @{self.url}'
    
class Job_Application(models.Model): 
    
    STATUS_CHOICES = (
        ('applied', 'Applied'), 
        ('will_apply', 'Will Apply'), 
        ('heard_back', 'Heard Back'), 
        ('interview', 'Interviewing'), 
        ('offered', 'Offered'), 
        ('rejected', 'Rejected'), 
        ('ghosted', 'Ghosted')
    )

    role = models.CharField(max_length=150)
    url = models.CharField(max_length=250)
    company = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    salary = models.CharField(max_length=100) 
    date = models.DateField('Date')
    location = models.CharField(max_length=100) 
    status = models.CharField(
        max_length=50, 
        choices=STATUS_CHOICES, 
        default='applied'
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return self.role
    
    def get_absolute_url(self): 
        return reverse('applications_detail', kwargs= {'user_id': self.user_id, 'application_id': self.id} )
    
class Application_Component(models.Model): 
    type = models.CharField(max_length=150)
    date = models.DateField('Date')
    contact = models.CharField(max_length=200) 
    description = models.TextField(max_length=500)
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    application = models.ForeignKey(
        Job_Application, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'note id: {self.id}'
    
    class Meta: 
        ordering = ['-date']
    

class Component_Note(models.Model): 
    content = models.TextField(max_length=400)
    date = models.DateField(auto_now_add=True)
    component = models.ForeignKey(
        Application_Component, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'note id: {self.id}'

    class Meta: 
        ordering = ['-date']

    
class Pdf(models.Model): 
    url = models.CharField(max_length=200)
    job_application = models.ForeignKey(
        Job_Application, 
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'PDF for job_application: {self.job_application_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Post, Comment,Company_Subforum, Company_Post, Company_Comment, Subforum, Job_Application, Component_Note, Application_Component

class PostForm(ModelForm): 
    class Meta: 
        model = Post 
        fields = ['content']

class SubforumForm(ModelForm): 
    class Meta: 
        model = Subforum 
        fields = ['title', 'pinned', 'content']

class CommentForm(ModelForm): 
    class Meta: 
        model = Comment 
        fields = ['content']

class Company_SubforumForm(ModelForm): 
    class Meta: 
        model = Company_Subforum 
        fields = ['title', 'pinned', 'content']

class Company_PostForm(ModelForm): 
    class Meta: 
        model = Company_Post 
        fields = ['content']

class Company_CommentForm(ModelForm): 
    class Meta: 
        model = Company_Comment 
        fields = ['content']

class Job_ApplicationForm(ModelForm): 
    class Meta: 
        model = Job_Application
        fields = ['role', 'url', 'company', 'description', 'salary', 'date', 'location', 'status']

class Component_NoteForm(ModelForm): 
    class Meta: 
        model = Component_Note
        fields = ['content']

class Application_ComponentForm(ModelForm): 
    class Meta: 
        model = Application_Component
        fields = ['type', 'date', 'contact', 'description']

class StatusForm(ModelForm): 
    class Meta: 
        model = Job_Application
        fields = ['status']

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About The Draft</h1>

<h5>Welcome to The Draft, your go-to destination for all things related to the job search process. Whether you're a recent graduate taking your first steps into the job market or a seasoned professional looking to make a career change, The Draft is here to help you navigate the often complex and challenging world of job hunting.</h5>

<div class="card p-4 mt-4 mx-2">
    <h3>Our Mission</h3>
    <p>At The Draft, our mission is simple: to empower job seekers like you by providing a supportive and inclusive online community where you can connect, learn, and grow. We believe that the job search journey doesn't have to be a solitary endeavor. By coming together and sharing knowledge, experiences, and insights, we can all enhance our chances of success.</p>

    
    <h3>What Sets Us Apart</h3>
    <p>The Draft is not just another job search platform. We take pride in our unique features and the vibrant community that makes us stand out</p>

    <h4>Diverse and Inclusive Community</h4>
    <p>We welcome job seekers from all backgrounds, industries, and experience levels. Our diverse user base ensures that you can get advice and perspectives from a wide range of individuals.</p>  

    <h4>Ask Anything, Anytime</h4>
    <p>Our discussion forums are open 24/7, allowing you to ask questions about any aspect of your job search whenever it's convenient for you. Whether you need help with crafting the perfect resume, preparing for an interview, or negotiating a job offer, our community is here to assist.</p>


    <h4>Expert Advice</h4>
    <p>In addition to the wisdom of our community members, we also feature expert contributors who share their knowledge and insights on various job search topics. You'll find articles, webinars, and resources created by professionals with years of experience in the field.</p>

    <h4>Networking Opportunities</h4> 
    <p>We understand the importance of building a strong professional network. The Draft provides a space for you to connect with fellow job seekers, potential mentors, and industry experts. Expand your network and open doors to new opportunities.</p>        

    <h4>Privacy and Security</h4>
    <p>We take your privacy and security seriously. Your personal information is safeguarded, and we encourage respectful and constructive interactions within our community.</p>    

    <h3>Join the The Draft Community Today</h3>
    <p>Whether you're just starting your job search or looking to fine-tune your strategy, The Draft is your trusted partner in achieving your career goals. Join our community today, and let's embark on this journey together. Together, we'll make your job search more manageable, more successful, and even more enjoyable.</p>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>The Draft</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://use.typekit.net/mxv1asd.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="{% static 'build/pdf.js' %}"></script>
    <script src="{% static 'web/viewer.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-footer-style">   
            <a class="navbar-brand" href="{% url 'home' %}">The Draft</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'faq' %}">FAQ</a>
                    </li>
                    {% if user.is_authenticated %} 
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">General Subforums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company_index' %}">View Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' user.id %}">My Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'liked' user.id %}">Liked Subforums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>     
    </nav>
    <main class="container container-page">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2023 The Draft &nbsp;</div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>    
    <script src="https://kit.fontawesome.com/3c45e3f9fc.js" crossorigin="anonymous"></script>
</body>
</html>

main_app/templates/company-base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>The Draft</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.typekit.net/mxv1asd.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="{% static 'build/pdf.js' %}"></script>
    <script src="{% static 'web/viewer.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-footer-style">   
            <a class="navbar-brand" href="{% url 'home' %}">The Draft</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %} 
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">General Subforums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company_index' %}">View Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' user.id %}">My Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>     
    </nav>
    <main class="container container-page px-0 pt-0">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="justify-content p-1 border-bottom">
          <!-- Left -->
          <!-- Right -->
        </section>
      
        <!-- Section: Links  -->
        <section class="">
          <div class="container text-center text-md-start mt-2">
            <!-- Grid row -->
            <div class="row mt-2">
              <!-- Grid column -->
              <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-2">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                  <i class="fa-solid fa-laptop me-3"></i>The Draft
                </h6>
                <p>
                    Welcome to The Draft, your go-to destination for all things related to the job search process. We're here to help you navigate the often complex and challenging world of job hunting.
                </p>
              </div>
              <!-- Grid column -->
      
              <!-- Grid column -->
              <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-2">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                  Technologies Used
                </h6>
                <p>
                  <a href="https://www.djangoproject.com/" class="text-reset" target="_blank" rel="noopener noreferrer">Django</a>
                </p>
                <p>
                  <a href="https://getbootstrap.com/" class="text-reset" target="_blank" rel="noopener noreferrer">Bootstrap</a>
                </p>
                <p>
                  <a href="https://aws.amazon.com/s3/" class="text-reset" target="_blank" rel="noopener noreferrer">AWS</a>
                </p>
                <p>
                  <a href="https://mozilla.github.io/pdf.js/" class="text-reset" target="_blank" rel="noopener noreferrer">PDF.js</a>
                </p>
              </div>
              <!-- Grid column -->
      
              <!-- Grid column -->
              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-2">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                  Useful links
                </h6>
                <p>
                  <a href="{% url 'home' %}" class="text-reset">Home</a>
                </p>
                <p>
                  <a href="{% url 'about' %}" class="text-reset">About</a>
                </p>
                <p>
                  <a href="{% url 'faq' %}" class="text-reset">FAQ</a>
                </p>
                <p>
                  <a href="{% url 'help' %}" class="text-reset">Help</a>
                </p>
              </div>
              <!-- Grid column -->
      
            </div>
            <!-- Grid row -->
          </div>
        </section>
        <!-- Section: Links  -->
      
        <!-- Copyright -->
        <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
          © 2023 All Rights Reserved:
          <strong>The Draft </strong>
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>    
        <script src="https://kit.fontawesome.com/3c45e3f9fc.js" crossorigin="anonymous"></script>
    </body>
    </html>
    
    

main_app/templates/help.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="card p-4">
    sorry, we're busy trying to get jobs too ¯\_(ツ)_/¯
</div>

{% endblock %}

main_app/templates/home.html
{% extends 'home-base.html' %}
{% block content %}


{% load static %}


<section class="about-us">
    <div id="about-us-text">
        <h2>About Us</h2>
        <p id="about"> Welcome to The Draft, the ultimate destination for tech enthusiasts and job seekers in the ever-evolving world of technology. <br>
            Engage yourself with in-depth discussions and access expert insights to supercharge your tech career. <br>
            Whether you're aiming to land your dream job, navigate career transitions, or simply stay updated on industry trends,<br> The Draft is your go-to platform. <br>
            Join us today and embark on a journey to enhance your tech career prospects. </p>
    </div>
</section>

<div class="container container-page" >
    <h2>List of General Topics</h2>

    {% if user.is_authenticated %}
        <a href="{% url 'subforums_new' %}">
            <button class="btn-add mb-3" style="border-radius: 0.5em;">Create A Subforum</button>
        </a>
    {% endif %}

    {% for subforum in subforums|dictsortreversed:"pinned" %}
        <a href="{% url 'subforums_detail' subforum.id %}">
            <div class="card mb-3 p-4" style="border-radius: 0.5em;">
                <div style="display: flex;">
                    {% if subforum.pinned %}
                    <span class="pin-icon" style="padding-top: 0.3rem;">&#x1F4CC;</span> <!-- Add a pin icon here -->
                    <h5 class="card-title" style="margin-left: 1rem;">{{ subforum.title }}</h5>
                    {% else %}
                    <h5 class="card-title">{{ subforum.title }}</h5>
                    {% endif %} 
                </div>
                <p class="card-text">By: {{ subforum.user }}</p>
                <p class="card-text">On: {{ subforum.date }}</p>
                <p class="card-text">Likes: {{ subforum.subforum_likes_set.all | length }}</p>
            </div>
        </a>
    {% endfor %}



    {% block script %}

    <script>
        
        const myText = document.getElementById("about")

        function updateText(e) {
            multiplierWidth = e.offsetX / window.innerWidth;
            multiplierHeight = e.offsetY / window.innerHeight;
            randomWeight =  multiplierWidth * (700 - 100) + 500;
            randomWidth =  multiplierHeight * (100 - 50) + 150;
            // myText.style.fontVariationSettings = "\"wght\" " + randomWeight + ", \"wdth\" " + randomWidth;
            myText.style.fontVariationSettings = "\"wght\" " + randomWeight;
        }
        window.addEventListener("mousemove", updateText)

        const collapseElementList = document.querySelectorAll('.collapse')
        const collapseList = [...collapseElementList].map(collapseEl => new bootstrap.Collapse(collapseEl))
    </script>

    {% endblock %}
</div>
{% endblock %}