main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('help/', views.help, name='help'),
	path('subforums/new/', views.subforums_new, name='subforums_new'),
	path('subforums/create/', views.subforums_create, name='subforums_create'),
	path('subforums/<int:subforum_id>/', views.subforums_detail, name='subforums_detail'),
	path('subforums/<int:subforum_id>/like/', views.subforums_like, name='subforums_like'),
	path('subforums/<int:pk>/update/', views.SubforumUpdate.as_view(), name='subforums_update'),
	path('subforums/<int:subforum_id>/add_post/', views.add_post, name='add_post'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/update/', views.update_post, name='update_post'),
	path('subforums/<int:subforum_id>/post/<int:pk>/delete/', views.PostDelete.as_view(), name='delete_post'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
  	path('subforums/<int:subforum_id>/post/<int:post_id>/comment/<int:pk>/delete_comment/', views.CommentDelete.as_view(), name='delete_comment'),
	path('company/', views.CompanyList.as_view(), name='company_index'),
	path('company/<int:pk>/', views.CompanyDetail.as_view(), name='company_detail'),
	path('company/create/', views.CompanyCreate.as_view(), name='company_create'),
	path('company/<int:company_id>/subforums/new/', views.company_subforums_new, name='company_subforums_new'),
	path('company/<int:company_id>/subforums/create/', views.company_subforums_create, name='company_subforums_create'),
	path('company/<int:company_id>/subforums/<int:pk>/update/', views.Company_SubforumUpdate.as_view(), name='company_subforums_update'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/', views.company_subforums_detail, name='company_subforums_detail'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/like/', views.company_subforums_like, name='company_subforums_like'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/add_post/', views.add_company_post, name='add_company_post'),
    path('company/<int:company_id>/subforums/<int:company_subforum_id>/post/<int:company_post_id>/add_comment/', views.add_company_comment, name='add_company_comment'),
    path('company/<int:company_id>/subforums/<int:company_subforum_id>/post/<int:company_post_id>/comment/<int:pk>/delete/', views.Company_CommentDelete.as_view(), name='delete_company_comment'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/posts/<int:company_post_id>/update/', views.update_company_post, name='update_company_post'),
	path('company/<int:company_id>/subforums/<int:company_subforum_id>/posts/<int:pk>/delete/', views.Company_PostDelete.as_view(), name='delete_company_post'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/<int:user_id>/application/new/', views.applications_new, name='applications_new'),
    path('profile/<int:user_id>/application/create/', views.applications_create, name='applications_create'),
    path('profile/<int:user_id>/application/<int:application_id>/', views.applications_detail, name='applications_detail'),
    path('profile/<int:user_id>/application/<int:pk>/delete/', views.Job_ApplicationDelete.as_view(), name='applications_delete'),
    path('profile/<int:user_id>/application/<int:pk>/update/', views.Job_ApplicationUpdate.as_view(), name='applications_update'),
    path('profile/<int:user_id>/application/<int:application_id>/status_update/', views.status_update, name='status_update'),
    path('profile/<int:user_id>/application/<int:application_id>/add_component/', views.add_component, name='add_component'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:pk>/delete/', views.Application_ComponentDelete.as_view(), name='delete_component'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:component_id>/add_note/', views.add_note, name='add_note'),
    path('profile/<int:user_id>/application/<int:application_id>/component/<int:component_id>/note/<int:pk>/delete/', views.Component_NoteDelete.as_view(), name='delete_note'),
    path('profile/<int:user_id>/liked/', views.liked, name='liked'),
  	path('accounts/signup/', views.signup, name='signup'), 
	path('faq/', views.faq, name='faq')
]

thedraft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date, datetime
from django.contrib.auth.models import User 
# Create your models here.


class Subforum(models.Model): 
    title = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    pinned = models.BooleanField(default=False)
    content = models.TextField(max_length=600)
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'title of this subforum: {self.title}'
    
    def get_absolute_url(self): 
        return reverse('subforums_detail', kwargs={'subforum_id': self.id})  #refactor with the correct views reference and variable names 
    
class Subforum_Likes(models.Model): 
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    subforum = models.ForeignKey(
        Subforum, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'likes model {self.id} '

    
class Post(models.Model): 
    content = models.TextField(max_length=600)
    date = models.DateField(auto_now_add=True)
    subforum = models.ForeignKey(
        Subforum, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
  
    def __str__(self):
        return f'the id of this post is {self.id}'
    
    def get_absolute_url(self): 
        return reverse('subforums_detail', kwargs={'subforum_id': self.subforum.id}) 

    class Meta: 
        ordering = ['-date']

class Photo(models.Model): 
    url = models.CharField(max_length=200)
    subforum = models.ForeignKey(
        Subforum, 
        on_delete=models.CASCADE
        )
    

    def __str__(self):
        return f'photo id: {self.id} @{self.url}'



class Comment(models.Model): 
    content = models.TextField(max_length=250)
    date = models.DateField(auto_now_add=True)
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'comment id: {self.id}'

    class Meta: 
        ordering = ['-date']

class Company(models.Model): 
    name =  models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    url = models.CharField(max_length=150, verbose_name='Company Job Postings URL')
    industry = models.CharField(max_length=100)
    photo_url = models.CharField(max_length=150)

    def __str__(self): 
        return f'{self.name}'
    
    def get_absolute_url(self): 
        return reverse('company_detail', kwargs={'pk': self.id})  #refactor with the correct views reference and variable names 
    

class Company_Subforum(models.Model): 
    title = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    pinned = models.BooleanField(default = False)
    content = models.TextField(max_length=600)
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'title subforum: {self.title}'
    
    def get_absolute_url(self): 
        return reverse('company_subforums_detail', kwargs={
            'company_id': self.company_id,
            'company_subforum_id': self.id
            })  #refactor with the correct views reference and variable names 

class Company_Subforum_Likes(models.Model): 
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    subforum = models.ForeignKey(
        Company_Subforum, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return f'likes model {self.id} '
    
class Company_Post(models.Model): 
    content = models.TextField(max_length=600)
    date = models.DateField(auto_now_add=True)
    subforum = models.ForeignKey(
        Company_Subforum, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
  
    def __str__(self):
        return f'post id: {self.id}'

    class Meta: 
        ordering = ['-date']

class Company_Comment(models.Model): 
    content = models.TextField(max_length=250)
    date = models.DateField(auto_now_add=True)
    post = models.ForeignKey(
        Company_Post, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    def __str__(self):
        return f'comment id: {self.id}'

    class Meta: 
        ordering = ['-date']

class Company_Photo(models.Model): 
    url = models.CharField(max_length=200)
    subforum = models.ForeignKey(
        Company_Subforum, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'Photo id: {self.id} @{self.url}'
    
class Job_Application(models.Model): 
    
    STATUS_CHOICES = (
        ('applied', 'Applied'), 
        ('will_apply', 'Will Apply'), 
        ('heard_back', 'Heard Back'), 
        ('interview', 'Interviewing'), 
        ('offered', 'Offered'), 
        ('rejected', 'Rejected'), 
        ('ghosted', 'Ghosted')
    )

    role = models.CharField(max_length=150)
    url = models.CharField(max_length=250)
    company = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    salary = models.CharField(max_length=100) 
    date = models.DateField('Date')
    location = models.CharField(max_length=100) 
    status = models.CharField(
        max_length=50, 
        choices=STATUS_CHOICES, 
        default='applied'
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self): 
        return self.role
    
    def get_absolute_url(self): 
        return reverse('applications_detail', kwargs= {'user_id': self.user_id, 'application_id': self.id} )
    
class Application_Component(models.Model): 
    type = models.CharField(max_length=150)
    date = models.DateField('Date')
    contact = models.CharField(max_length=200) 
    description = models.TextField(max_length=500)
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )
    application = models.ForeignKey(
        Job_Application, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'note id: {self.id}'
    
    class Meta: 
        ordering = ['-date']
    

class Component_Note(models.Model): 
    content = models.TextField(max_length=400)
    date = models.DateField(auto_now_add=True)
    component = models.ForeignKey(
        Application_Component, 
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'note id: {self.id}'

    class Meta: 
        ordering = ['-date']

    
class Pdf(models.Model): 
    url = models.CharField(max_length=200)
    job_application = models.ForeignKey(
        Job_Application, 
        on_delete=models.CASCADE
        )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'PDF for job_application: {self.job_application_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Post, Comment,Company_Subforum, Company_Post, Company_Comment, Subforum, Job_Application, Component_Note, Application_Component

class PostForm(ModelForm): 
    class Meta: 
        model = Post 
        fields = ['content']

class SubforumForm(ModelForm): 
    class Meta: 
        model = Subforum 
        fields = ['title', 'pinned', 'content']

class CommentForm(ModelForm): 
    class Meta: 
        model = Comment 
        fields = ['content']

class Company_SubforumForm(ModelForm): 
    class Meta: 
        model = Company_Subforum 
        fields = ['title', 'pinned', 'content']

class Company_PostForm(ModelForm): 
    class Meta: 
        model = Company_Post 
        fields = ['content']

class Company_CommentForm(ModelForm): 
    class Meta: 
        model = Company_Comment 
        fields = ['content']

class Job_ApplicationForm(ModelForm): 
    class Meta: 
        model = Job_Application
        fields = ['role', 'url', 'company', 'description', 'salary', 'date', 'location', 'status']

class Component_NoteForm(ModelForm): 
    class Meta: 
        model = Component_Note
        fields = ['content']

class Application_ComponentForm(ModelForm): 
    class Meta: 
        model = Application_Component
        fields = ['type', 'date', 'contact', 'description']

class StatusForm(ModelForm): 
    class Meta: 
        model = Job_Application
        fields = ['status']

main_app/templates/subforum/detail.html
{% extends 'base.html' %}
{% block content %}

{% load static %}


<div class="mb-3">
    <h1>{{ subforum.title }}</h1>
    <div style="display: flex; justify-content: end;">
        <form class="like-button-form" method="POST">
            {% csrf_token %}
            {% if is_liked %}
                <i class="fa-solid fa-heart fa-2xl like-button" style="color: red; font-size: 8vmin; text-shadow: 3px 3px 5px rgba(0,0,0,0.77);"></i>
            {% else %}
                <i class="fa-solid fa-heart fa-2xl like-button" style="color: white; font-size: 8vmin; text-shadow: 3px 3px 5px rgba(0,0,0,0.77);"></i>
            {% endif %}
        </form>
    </div>
    <small>By: {{ subforum.user }}</small><br>
    <small>Created: {{ subforum.date }}</small><br>
    <small>Likes: <span id="likes"> {{ likes }} </span> </small> 
    <p> {{ subforum.content }} </p>
    {% if subforum.photo_set.all %}
        <div id="carouselExample" class="carousel slide mx-auto" style="width: 40vmax; height: 80vmin;">
            <div class="carousel-inner">
            {% for photo in subforum.photo_set.all %}
                <div class="carousel-item active">
                    <img src=" {{ photo.url }} " class="d-block w-100 mb-4" style="max-width: 40vmax;">
                </div>
            {% empty %}
                <div>No Photos Uploaded</div>
            {% endfor %}
                </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>
  {% endif %}
    
    {% if user == subforum.user %}
        <form class="my-2" action=" {% url 'subforums_update' subforum.id %} ">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Edit Subforum">
        </form>
    {% endif %}
</div>
<p class="d-inline-flex gap-1 mb-2">
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" id="expand-btn">
        Expand Comments
    </button>
</p>

<div class="row px-2 py-2 my-2" id="post-body">
    {% for post in subforum.post_set.all %}
        <div class="card py-2 my-2">
            <h5 class="card-title">Post by User: {{ post.user }} </h5>
            <small>Created: {{ post.date }}</small><br>
            <p>{{ post.content }}</p>
            {% if user == post.user %}
                <form action=" {% url 'delete_post' subforum.id post.id %} ">
                    {% csrf_token %}
                    <input type="submit" class="btn-delete" value="Delete Post">
                </form>
            {% endif %}
        </div>
        <div class="collapse" id="collapseExample">
            <div class="comment-container">
                {% for comment in post.comment_set.all %}
                    <div class="comment mb-2 p-2">
                        <p > {{ comment.user }} Commented:<br>
                           <small> {{ comment.date }} </small><br>
                            {{ comment.content }} </p>
                        {% if user == comment.user %}
                            <form action=" {% url 'delete_comment' subforum.id post.id comment.id %} ">
                                {% csrf_token %}
                                <input type="submit" class="btn-delete" value="Delete Comment">
                            </form>
                        {% endif %}
                    </div>
                {% endfor %}
                {% if user.is_authenticated %}
                    <form class=" mb-2" action=" {% url 'add_comment' subforum.id post.id %} " method="POST">
                        {% csrf_token %}
                        <table>
                            {{ comment_form.as_table }}
                        </table>
                        <input type="submit" class="btn-add" value="Add A Comment">
                    </form>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

<div class="row mt-4">
    <h2>Add a Post</h2>
    {% if user.is_authenticated %}
        <form action="{% url 'add_post' subforum.id %}" method="POST">
            {% csrf_token %}
            {{ post_form.as_p }}
            <button type="submit" class="btn btn-primary">Add Post</button>
        </form>
    {% endif %}
</div>


{% block scripts %}
<script>
    $(document).ready(function() {
        $('.like-button-form').click(function(event) {
            event.preventDefault();
            let form =$(this)
            let button = document.querySelector('.like-button')
            let likes= document.querySelector('#likes')
            $.ajax({
                url: "{% url 'subforums_like' subforum.id %}", 
                type: "POST", 
                data: form.serialize(), 
                dataType: "json", 
                success: function(data) {
                    if (data.success) {
                        likes.innerText = data.likes
                        data.is_liked ? button.style.color = 'red' : button.style.color = 'white'
                        console.log(`success!, likes: ${data.likes} `)
                    } else {
                        alert('failed to add a like to the subforum')
                    }
                }, 
                error: function() {
                    alert('server failed to add a like')
                }
            })
        } )
    } )

    const expand = document.querySelector('#expand-btn')
    expand.addEventListener('click', changeText)

    function changeText(event) {
        expand.innerText = expand.innerText === "Collapse Comments" ? "Expand Comments": "Collapse Comments"
    }

    $(document).ready(function() {
        $("#id_date").datepicker({format:"yyyy-mm-dd"})
    })
</script>

{% endblock %}
{% endblock %}

main_app/templates/subforum/form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Add Subforum</h1>
  <form action=" {% url 'subforums_create' %} " enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <table>
      {{ subforum_form.as_table }}
    </table>
    <strong>Add Images to Your Post:</strong> <input type="file" name="photo-file" multiple>
    <button type="submit" class="btn btn-primary">Add Subforum</button>
  </form>
{% endblock %}

main_app/templates/subforum/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}